using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.IO;
using System.Numerics;
using System.Linq;
using System.Text;
using System.Threading;

namespace PerfectCuboid
{
    //For any PT, we can generate a Euler Brick, per "Pythagorean Triangles" by Waclaw Sierpinski, P105, Theorem 15.17: For a PT(a, b, c), we can have Euler Brick:
    //X = a^2 * |4b^2 - c^2|
    //Y = b^2 * |4a^2 - c^2|
    //Z = 4abc

    //Only need to check PT for primitive perfect cuboid, if there is any.
    class EulerBrick
    {
        private object _locker = new object();
        private UInt64 _low;
        private UInt64 _high;
        private TextWriter _tw;

        private Int64 _totalSearchCount = 0;
        private Int64 _totalPerfectCuboidFound = 0;
        private int _totalThreads = 10;
        private DataSet _maxSearchedCandidate = new DataSet();

        public EulerBrick(UInt64 low, UInt64 high, TextWriter tw)
        {
            _low = low;
            _high = high;
            _tw = tw;
            _maxSearchedCandidate.check = 0;
        }

        public UInt64 SeachEulerBrick()
        {
            NameValueCollection appSettings = ConfigurationManager.AppSettings;
            _totalThreads = int.Parse(appSettings["Threads"]);

            Thread[] threads = new Thread[_totalThreads];
            ParameterizedThreadStart start = new ParameterizedThreadStart(SearchEulerBrickThread);
            for (int i = 0; i < _totalThreads; i++)
            {
                threads[i] = new Thread(start);
            }

            // for each m
            UInt64 m = _low;
            UInt64 scope = 100;
            UInt64 displayScope = (_high - _low) >> 6; // display 64 chunks for progress
            if (displayScope == 0)
            {
                displayScope = 1;
            }
            UInt64 displayThreshold = _low + displayScope;
            int displayCount = 0;
            bool runningThread = false;
            while (m < _high)
            {
                runningThread = false;
                for (int i = 0; i < _totalThreads; i++)
                {
                    if (!threads[i].IsAlive)
                    {
                        ThreadParameters tps = new ThreadParameters();
                        tps.Low = m + 1;
                        m += scope;
                        tps.High = m;
                        tps.ThreadID = i;
                        tps.dl = null;

                        threads[i] = new Thread(start);
                        threads[i].Start(tps);

                        runningThread = true;
                        if (m >= _high)
                        {
                            break;
                        }
                    }
                }

                if (m > displayThreshold)
                {
                    displayCount++;
                    Utils.Output(_tw, string.Format(".Calculated {0}: m/_high = {1}/{2}. DateTime={3}", displayCount, m, _high, DateTime.Now));
                    displayThreshold += displayScope;
                }

                if (!runningThread)
                {
                    Thread.Sleep(500);
                }
            }

            runningThread = true;
            while (runningThread)
            {
                runningThread = false;
                for (int i = 0; i < _totalThreads; i++)
                {
                    if (threads[i].IsAlive)
                    {
                        runningThread = true;
                        break;
                    }
                }

                Thread.Sleep(3000);
            }

            Utils.Output(_tw, string.Format("time:{0} checked:{1} found:{2}, maxSearched:{3}",
                DateTime.Now, _totalSearchCount, _totalPerfectCuboidFound, _maxSearchedCandidate));

            return (UInt64)_totalPerfectCuboidFound;
        }

        private void SearchEulerBrickThread(object obj)
        {
            ThreadParameters parameters = (ThreadParameters)obj;

            // Low to high should be UInt32, which covers 2*2^32*2^32 = 2*264
            UInt64 from = parameters.Low; // + (parameters.Low & 0x1);
            UInt64 to = parameters.High > _high ? _high : parameters.High;
            for (UInt64 m = from; m <= to; m++) // m must be even
            {
                // calculate each n

                // only m and n is not the same odd/even then it generates PPT
                //if ((m & 1) != (n & 1))

                for (UInt64 n = 1 + (m & 1); n < m; n += 2)
                {
                    // Non-coprime parameters only produce scaled copies of a brick
                    // generated by their reduced parameters.
                    if (PerfectCuboidMath.GreatestCommonDivisor(m, n) != 1)
                    {
                        continue;
                    }

                    DataSet ds = new DataSet(m, n);
                    //DataSet1 ds = new DataSet1(m, n);

                    // if ((ds.c & 0x1)==1 && ds.check.IsOdd()) // C, G, and Check are always odd here
                    {
                        if (ds.DataCheck())
                        {
                            System.Threading.Interlocked.Increment(ref _totalPerfectCuboidFound);
                            Utils.Output(_tw, string.Format("Haha: found one! total found: {0}, ds:{1}",
                                _totalPerfectCuboidFound, ds));
                            Console.ReadLine();
                        }
                    }

                    if (ds.valid && ds.check > _maxSearchedCandidate.check)
                    {
                        lock (_locker)
                        {
                            if (ds.valid && ds.check > _maxSearchedCandidate.check)
                            {
                                _maxSearchedCandidate = ds;
                            }
                        }
                    }

                    // interlock to increase _totalSearchCount and _totalFoundCount, if there is any.
                    System.Threading.Interlocked.Increment(ref _totalSearchCount);
                    if ((_totalSearchCount & 0xffffffff) == 0)
                    {
                        Utils.Output(_tw, string.Format("time:{0} checked:{1} found:{2}, maxSearched:{3}",
                            DateTime.Now, _totalSearchCount, _totalPerfectCuboidFound, _maxSearchedCandidate));
                    }
                    else if ((_totalSearchCount & 0xfffffff) == 0)
                    {
                        Console.Write(".");
                    }
                }
            }
        }

        public UInt64 GenerateAllEulerBricks()
        {
            UInt64 found = 0;
            for (UInt64 i = _low; i < _high; i++)
            {
                for (UInt64 j = _low; j < i; j++)
                {
                    for (UInt64 k = _low; k < j; k++)
                    {
                        BigInteger i2 = i * i;
                        BigInteger j2 = j * j;
                        BigInteger k2 = k * k;
                        if (Utils.IsPerfectSquare(i2+j2) && Utils.IsPerfectSquare(j2+k2) && Utils.IsPerfectSquare(k2+i2))
                        {
                            BigInteger G = i2 + j2 + k2;
                            found++;
                            Utils.Output(_tw, string.Format("{0}:\t{1}^2+{2}^2+{3}^2={4}", found, i, j, k, G));
                        }
                    }
                }
            }

            return found;
        }
    }

    class CompleteEulerSearchOptions
    {
        public UInt64 SmallestEdgeFrom;
        public UInt64 SmallestEdgeTo;
        public string CheckpointPath;
        public string ResultsPath;
        public UInt64 MaxMemoryMB;
        public UInt64 CheckpointEveryVertices = 1000;
        public int ProgressSeconds = 10;
        public bool Resume = true;

        public void Validate(UInt64 low, UInt64 high)
        {
            if (SmallestEdgeFrom < low || SmallestEdgeFrom > high)
            {
                throw new ArgumentOutOfRangeException(
                    "SmallestEdgeFrom",
                    "The shard start must be inside the global edge range.");
            }
            if (SmallestEdgeTo < SmallestEdgeFrom || SmallestEdgeTo > high)
            {
                throw new ArgumentOutOfRangeException(
                    "SmallestEdgeTo",
                    "The shard end must be between the shard start and global maximum edge.");
            }
            if (CheckpointEveryVertices == 0)
            {
                throw new ArgumentOutOfRangeException(
                    "CheckpointEveryVertices",
                    "Checkpoint frequency must be positive.");
            }
            if (ProgressSeconds <= 0)
            {
                throw new ArgumentOutOfRangeException(
                    "ProgressSeconds",
                    "Progress interval must be positive.");
            }
            if (!string.IsNullOrEmpty(CheckpointPath) &&
                !string.IsNullOrEmpty(ResultsPath) &&
                string.Equals(
                    Path.GetFullPath(CheckpointPath),
                    Path.GetFullPath(ResultsPath),
                    StringComparison.OrdinalIgnoreCase))
            {
                throw new ArgumentException("Checkpoint and results paths must be different.");
            }
        }
    }

    class CompleteEulerSearchResult
    {
        public UInt64 PythagoreanPairs;
        public UInt64 GraphTriangles;
        public UInt64 PrimitiveEulerBricks;
        public UInt64 NecessaryFilterSurvivors;
        public UInt64 ResidueSieveSurvivors;
        public UInt64 PerfectCuboids;
    }

    class CompleteEulerCheckpoint
    {
        public UInt64 CompletedThrough;
        public bool Done;
    }

    /// <summary>
    /// Finds every primitive Euler brick whose three edges are in [low, high].
    /// Vertices are edge lengths and an edge connects two lengths when they form
    /// the legs of a Pythagorean triangle. A graph triangle is therefore an Euler brick.
    /// </summary>
    class CompleteEulerBrickSearch
    {
        private readonly UInt64 _low;
        private readonly UInt64 _high;
        private readonly TextWriter _output;
        private readonly CompleteEulerSearchOptions _options;
        private readonly Dictionary<UInt64, HashSet<UInt64>> _adjacency =
            new Dictionary<UInt64, HashSet<UInt64>>();
        private readonly HashSet<string> _recordedPerfectCuboids = new HashSet<string>();

        public CompleteEulerBrickSearch(UInt64 low, UInt64 high, TextWriter output)
            : this(low, high, output, CreateDefaultOptions(low, high))
        {
        }

        public CompleteEulerBrickSearch(
            UInt64 low,
            UInt64 high,
            TextWriter output,
            CompleteEulerSearchOptions options)
        {
            if (low == 0)
            {
                throw new ArgumentOutOfRangeException("low", "The minimum edge must be positive.");
            }
            if (high < low)
            {
                throw new ArgumentException("The maximum edge must be at least the minimum edge.");
            }

            _low = low;
            _high = high;
            _output = output;
            _options = options ?? CreateDefaultOptions(low, high);
            _options.Validate(low, high);
        }

        private static CompleteEulerSearchOptions CreateDefaultOptions(UInt64 low, UInt64 high)
        {
            CompleteEulerSearchOptions options = new CompleteEulerSearchOptions();
            options.SmallestEdgeFrom = low;
            options.SmallestEdgeTo = high;
            return options;
        }

        public CompleteEulerSearchResult Search()
        {
            CompleteEulerSearchResult result = new CompleteEulerSearchResult();
            CompleteEulerCheckpoint checkpoint = InitializePersistence();
            if (checkpoint.Done)
            {
                Utils.Output(_output, "Checkpoint already marks this shard complete; no work is required.");
                return result;
            }

            Utils.Output(_output, string.Format(
                "Complete Euler shard: globalEdges=[{0},{1}], smallestEdge=[{2},{3}], " +
                "resumeAfter={4}, maxMemoryMB={5}",
                _low,
                _high,
                _options.SmallestEdgeFrom,
                _options.SmallestEdgeTo,
                checkpoint.CompletedThrough,
                _options.MaxMemoryMB == 0 ? "unlimited" : _options.MaxMemoryMB.ToString()));

            BuildPythagoreanGraph(result);

            Utils.Output(_output, string.Format(
                "Complete Euler graph built: vertices={0}, Pythagorean pairs={1}",
                _adjacency.Count,
                result.PythagoreanPairs));

            HashSet<string> primitiveBricks = new HashSet<string>();
            List<UInt64> vertices = _adjacency.Keys.ToList();
            vertices.Sort();

            List<UInt64> shardVertices = vertices.Where(value =>
                value >= _options.SmallestEdgeFrom &&
                value <= _options.SmallestEdgeTo &&
                value > checkpoint.CompletedThrough).ToList();

            System.Diagnostics.Stopwatch stopwatch = System.Diagnostics.Stopwatch.StartNew();
            TimeSpan nextProgress = TimeSpan.FromSeconds(_options.ProgressSeconds);
            UInt64 processedVertices = 0;
            UInt64 completedThrough = checkpoint.CompletedThrough;

            foreach (UInt64 x in shardVertices)
            {
                HashSet<UInt64> xNeighbors = _adjacency[x];
                foreach (UInt64 y in xNeighbors)
                {
                    if (y <= x || !_adjacency.ContainsKey(y))
                    {
                        continue;
                    }

                    HashSet<UInt64> yNeighbors = _adjacency[y];
                    HashSet<UInt64> candidates =
                        xNeighbors.Count <= yNeighbors.Count ? xNeighbors : yNeighbors;
                    HashSet<UInt64> other =
                        xNeighbors.Count <= yNeighbors.Count ? yNeighbors : xNeighbors;

                    foreach (UInt64 z in candidates)
                    {
                        if (z <= y || !other.Contains(z))
                        {
                            continue;
                        }

                        result.GraphTriangles++;

                        BigInteger bx = new BigInteger(x);
                        BigInteger by = new BigInteger(y);
                        BigInteger bz = new BigInteger(z);
                        PerfectCuboidMath.Normalize(ref bx, ref by, ref bz);

                        // Scaled copies are discarded. Their primitive version is handled
                        // by the shard containing its own smallest edge.
                        if (bx != x || bx < _low || bz > _high)
                        {
                            continue;
                        }

                        string key = string.Format("{0}:{1}:{2}", bx, by, bz);
                        if (!primitiveBricks.Add(key))
                        {
                            continue;
                        }

                        result.PrimitiveEulerBricks++;
                        if (!PerfectCuboidMath.PassesNecessaryEdgeFilters(bx, by, bz))
                        {
                            continue;
                        }

                        result.NecessaryFilterSurvivors++;
                        BigInteger spaceDiagonalSquared = bx * bx + by * by + bz * bz;
                        if (!PerfectCuboidMath.PassesSquareResidueSieve(spaceDiagonalSquared))
                        {
                            continue;
                        }

                        result.ResidueSieveSurvivors++;
                        BigInteger spaceDiagonal =
                            PerfectCuboidMath.IntegerSquareRoot(spaceDiagonalSquared);
                        if (spaceDiagonal * spaceDiagonal == spaceDiagonalSquared)
                        {
                            result.PerfectCuboids++;
                            string discovery = string.Format(
                                "PERFECT CUBOID: {0}, {1}, {2}; space diagonal={3}",
                                bx,
                                by,
                                bz,
                                spaceDiagonal);
                            Utils.Output(_output, discovery);
                            RecordPerfectCuboid(key, discovery);
                        }
                    }
                }

                processedVertices++;
                completedThrough = x;
                if (processedVertices % _options.CheckpointEveryVertices == 0)
                {
                    SaveCheckpoint(completedThrough, false);
                }

                if (stopwatch.Elapsed >= nextProgress)
                {
                    OutputSearchProgress(
                        processedVertices,
                        (UInt64)shardVertices.Count,
                        completedThrough,
                        stopwatch.Elapsed,
                        result);
                    nextProgress = stopwatch.Elapsed +
                        TimeSpan.FromSeconds(_options.ProgressSeconds);
                    SaveCheckpoint(completedThrough, false);
                    CheckMemoryLimit("Euler-brick enumeration");
                }
            }

            SaveCheckpoint(
                completedThrough > 0 ? completedThrough : _options.SmallestEdgeTo,
                true);

            Utils.Output(_output, string.Format(
                "Complete Euler search: graphTriangles={0}, primitiveEulerBricks={1}, " +
                "necessaryFilterSurvivors={2}, residueSieveSurvivors={3}, perfectCuboids={4}",
                result.GraphTriangles,
                result.PrimitiveEulerBricks,
                result.NecessaryFilterSurvivors,
                result.ResidueSieveSurvivors,
                result.PerfectCuboids));

            AppendRunSummary(result, stopwatch.Elapsed);

            return result;
        }

        private CompleteEulerCheckpoint InitializePersistence()
        {
            CompleteEulerCheckpoint checkpoint = new CompleteEulerCheckpoint();
            LoadRecordedPerfectCuboids();

            if (string.IsNullOrEmpty(_options.CheckpointPath))
            {
                return checkpoint;
            }

            EnsureParentDirectory(_options.CheckpointPath);
            string fingerprint = GetCheckpointFingerprint();
            if (!_options.Resume || !File.Exists(_options.CheckpointPath))
            {
                using (StreamWriter writer = new StreamWriter(_options.CheckpointPath, false))
                {
                    writer.WriteLine("fingerprint=" + fingerprint);
                }
                return checkpoint;
            }

            string[] lines = File.ReadAllLines(_options.CheckpointPath);
            if (lines.Length == 0 || lines[0] != "fingerprint=" + fingerprint)
            {
                throw new InvalidDataException(
                    "Checkpoint does not match this global range and smallest-edge shard.");
            }

            for (int i = 1; i < lines.Length; i++)
            {
                string[] fields = lines[i].Split(';');
                foreach (string field in fields)
                {
                    if (field.StartsWith("completed=", StringComparison.Ordinal))
                    {
                        checkpoint.CompletedThrough =
                            UInt64.Parse(field.Substring("completed=".Length));
                    }
                    else if (field == "done=1")
                    {
                        checkpoint.Done = true;
                    }
                }
            }

            return checkpoint;
        }

        private string GetCheckpointFingerprint()
        {
            return string.Format(
                "v1|global={0}-{1}|smallest={2}-{3}",
                _low,
                _high,
                _options.SmallestEdgeFrom,
                _options.SmallestEdgeTo);
        }

        private void SaveCheckpoint(UInt64 completedThrough, bool done)
        {
            if (string.IsNullOrEmpty(_options.CheckpointPath))
            {
                return;
            }

            using (StreamWriter writer = new StreamWriter(_options.CheckpointPath, true))
            {
                writer.WriteLine(
                    "completed={0};done={1};utc={2}",
                    completedThrough,
                    done ? 1 : 0,
                    DateTime.UtcNow.ToString("o"));
            }
        }

        private void LoadRecordedPerfectCuboids()
        {
            if (string.IsNullOrEmpty(_options.ResultsPath) ||
                !File.Exists(_options.ResultsPath))
            {
                return;
            }

            foreach (string line in File.ReadAllLines(_options.ResultsPath))
            {
                if (line.StartsWith("key=", StringComparison.Ordinal))
                {
                    int separator = line.IndexOf('\t');
                    string key = separator < 0
                        ? line.Substring("key=".Length)
                        : line.Substring("key=".Length, separator - "key=".Length);
                    _recordedPerfectCuboids.Add(key);
                }
            }
        }

        private void RecordPerfectCuboid(string key, string discovery)
        {
            if (string.IsNullOrEmpty(_options.ResultsPath) ||
                !_recordedPerfectCuboids.Add(key))
            {
                return;
            }

            EnsureParentDirectory(_options.ResultsPath);
            using (StreamWriter writer = new StreamWriter(_options.ResultsPath, true))
            {
                writer.WriteLine(
                    "key={0}\tutc={1}\t{2}",
                    key,
                    DateTime.UtcNow.ToString("o"),
                    discovery);
            }
        }

        private void AppendRunSummary(CompleteEulerSearchResult result, TimeSpan elapsed)
        {
            if (string.IsNullOrEmpty(_options.ResultsPath))
            {
                return;
            }

            EnsureParentDirectory(_options.ResultsPath);
            using (StreamWriter writer = new StreamWriter(_options.ResultsPath, true))
            {
                writer.WriteLine(
                    "summary\tutc={0}\tglobal={1}-{2}\tsmallest={3}-{4}\t" +
                    "pairs={5}\ttriangles={6}\tprimitive={7}\tresidueSurvivors={8}\t" +
                    "perfect={9}\telapsed={10}",
                    DateTime.UtcNow.ToString("o"),
                    _low,
                    _high,
                    _options.SmallestEdgeFrom,
                    _options.SmallestEdgeTo,
                    result.PythagoreanPairs,
                    result.GraphTriangles,
                    result.PrimitiveEulerBricks,
                    result.ResidueSieveSurvivors,
                    result.PerfectCuboids,
                    elapsed);
            }
        }

        private void OutputSearchProgress(
            UInt64 processed,
            UInt64 total,
            UInt64 completedThrough,
            TimeSpan elapsed,
            CompleteEulerSearchResult result)
        {
            double percent = total == 0 ? 100.0 : (100.0 * processed / total);
            TimeSpan eta = TimeSpan.Zero;
            if (processed > 0 && processed < total)
            {
                double remainingSeconds =
                    elapsed.TotalSeconds * (total - processed) / processed;
                eta = TimeSpan.FromSeconds(remainingSeconds);
            }

            Utils.Output(_output, string.Format(
                "Progress: {0}/{1} smallest-edge vertices ({2:F2}%), through={3}, " +
                "EulerBricks={4}, residueSurvivors={5}, elapsed={6}, ETA={7}, memoryMiB={8}",
                processed,
                total,
                percent,
                completedThrough,
                result.PrimitiveEulerBricks,
                result.ResidueSieveSurvivors,
                elapsed,
                eta,
                GetManagedMemoryMB()));
        }

        private UInt64 GetManagedMemoryMB()
        {
            long bytes = GC.GetTotalMemory(false);
            return (UInt64)(bytes / (1024L * 1024L));
        }

        private void CheckMemoryLimit(string stage)
        {
            if (_options.MaxMemoryMB == 0)
            {
                return;
            }

            UInt64 used = GetManagedMemoryMB();
            if (used > _options.MaxMemoryMB)
            {
                throw new InvalidOperationException(string.Format(
                    "Memory ceiling exceeded during {0}: {1} MiB used, limit {2} MiB. " +
                    "Use a smaller global edge range or a larger memory limit.",
                    stage,
                    used,
                    _options.MaxMemoryMB));
            }
        }

        private static void EnsureParentDirectory(string path)
        {
            string directory = Path.GetDirectoryName(Path.GetFullPath(path));
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
        }

        private void BuildPythagoreanGraph(CompleteEulerSearchResult result)
        {
            BigInteger bigHigh = new BigInteger(_high);
            BigInteger maximumHypotenuse =
                PerfectCuboidMath.IntegerSquareRoot((bigHigh * bigHigh) << 1);
            UInt64 maximumM = (UInt64)PerfectCuboidMath.IntegerSquareRoot(maximumHypotenuse);
            System.Diagnostics.Stopwatch stopwatch = System.Diagnostics.Stopwatch.StartNew();
            TimeSpan nextProgress = TimeSpan.FromSeconds(_options.ProgressSeconds);

            for (UInt64 m = 2; m <= maximumM; m++)
            {
                for (UInt64 n = 1 + (m & 1); n < m; n += 2)
                {
                    if (PerfectCuboidMath.GreatestCommonDivisor(m, n) != 1)
                    {
                        continue;
                    }

                    BigInteger bigM = new BigInteger(m);
                    BigInteger bigN = new BigInteger(n);
                    BigInteger mSquared = bigM * bigM;
                    BigInteger nSquared = bigN * bigN;
                    BigInteger hypotenuse = mSquared + nSquared;
                    if (hypotenuse > maximumHypotenuse)
                    {
                        break;
                    }

                    BigInteger firstLeg = mSquared - nSquared;
                    BigInteger secondLeg = (bigM * bigN) << 1;
                    BigInteger smallerLeg = BigInteger.Min(firstLeg, secondLeg);
                    BigInteger largerLeg = BigInteger.Max(firstLeg, secondLeg);

                    UInt64 firstScale = (UInt64)((new BigInteger(_low) + smallerLeg - 1) / smallerLeg);
                    if (firstScale == 0)
                    {
                        firstScale = 1;
                    }
                    UInt64 lastScale = (UInt64)(bigHigh / largerLeg);

                    for (UInt64 scale = firstScale; scale <= lastScale; scale++)
                    {
                        UInt64 first = (UInt64)(firstLeg * scale);
                        UInt64 second = (UInt64)(secondLeg * scale);
                        if (first >= _low && second >= _low && AddEdge(first, second))
                        {
                            result.PythagoreanPairs++;
                        }

                        if (scale == UInt64.MaxValue)
                        {
                            break;
                        }
                    }
                }

                if ((m & 63) == 0)
                {
                    CheckMemoryLimit("Pythagorean graph generation");
                }

                if (stopwatch.Elapsed >= nextProgress)
                {
                    double percent = maximumM == 0 ? 100.0 : 100.0 * m / maximumM;
                    TimeSpan eta = m == 0
                        ? TimeSpan.Zero
                        : TimeSpan.FromSeconds(
                            stopwatch.Elapsed.TotalSeconds * (maximumM - m) / m);
                    Utils.Output(_output, string.Format(
                        "Graph progress: m={0}/{1} ({2:F2}%), pairs={3}, " +
                        "vertices={4}, elapsed={5}, ETA={6}, memoryMiB={7}",
                        m,
                        maximumM,
                        percent,
                        result.PythagoreanPairs,
                        _adjacency.Count,
                        stopwatch.Elapsed,
                        eta,
                        GetManagedMemoryMB()));
                    nextProgress = stopwatch.Elapsed +
                        TimeSpan.FromSeconds(_options.ProgressSeconds);
                }
            }

            CheckMemoryLimit("completed Pythagorean graph");
        }

        private bool AddEdge(UInt64 first, UInt64 second)
        {
            if (first == second)
            {
                return false;
            }

            HashSet<UInt64> firstNeighbors;
            if (!_adjacency.TryGetValue(first, out firstNeighbors))
            {
                firstNeighbors = new HashSet<UInt64>();
                _adjacency.Add(first, firstNeighbors);
            }

            HashSet<UInt64> secondNeighbors;
            if (!_adjacency.TryGetValue(second, out secondNeighbors))
            {
                secondNeighbors = new HashSet<UInt64>();
                _adjacency.Add(second, secondNeighbors);
            }

            bool added = firstNeighbors.Add(second);
            secondNeighbors.Add(first);
            return added;
        }
    }
}
